### ISSUE TITLE
Not working for my HP Envy 13 x360

### ISSUE THREAD

**Issue by Inovvia** [tagadvance/envy-x360#1]
Shows the following error:
Traceback (most recent call last):
  File "toggle-tablet-mode.py", line 37, in <module>
    main()
  File "toggle-tablet-mode.py", line 8, in main
    touchpad_id = get_touchpad()
  File "toggle-tablet-mode.py", line 20, in get_touchpad
    return m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Inovvia** [comment]
I was able to fix this by changing the keyboard and touchpad id's manually using ids i got from xinput list.

**Comment by tagadvance** [comment]
Hello Inovvia!

Thank you for the bug report.

Would you please provide me with the output of your xinput list so I can patch this?

Kind regards,

Tag

**Comment by Inovvia** [comment]
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech Gaming Mouse G402              	id=9	[slave  pointer  (2)]
⎜   ↳ Logitech Gaming Mouse G402 Consumer Control	id=11	[slave  pointer  (2)]
⎜   ↳ ELAN0732:00 04F3:2628                   	id=15	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=18	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Logitech Gaming Mouse G402 Keyboard     	id=10	[slave  keyboard (3)]
    ↳ Logitech Gaming Mouse G402 System Control	id=12	[slave  keyboard (3)]
    ↳ HP Wide Vision HD Camera: HP Wi         	id=13	[slave  keyboard (3)]
    ↳ HP IR Camera: HP IR Camera              	id=14	[slave  keyboard (3)]
    ↳ ELAN0732:00 04F3:2628                   	id=16	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=17	[slave  keyboard (3)]
    ↳ HP Wireless hotkeys                     	id=19	[slave  keyboard (3)]
    ↳ HP WMI hotkeys                          	id=20	[slave  keyboard (3)]
    ↳ Logitech Gaming Mouse G402 Consumer Control	id=21	[slave  keyboard (3)]

**Comment by tagadvance** [comment]
It looks like I should make the touchpad matcher ignore case. I have no idea why the keyboard wouldn't be disabled though. I should have a patch out within the hour.

**Comment by tagadvance** [comment]
It's because I looked up both IDs before sending the command to disable either one. Please pull down the latest changes with `git pull` and you should be good to go!
